spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: demo_exchange
  routingKey: demo_routingKey

spring.zipkin.base-url: http://localhost:9411
spring.sleuth.sampler.probability: 1.0
